import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from '@next/font/google'
// import styles from '../styles/Home.module.css'
import { HStack, VStack } from '@chakra-ui/react'
import Profile from '../.next/Component/Profile'
import Tech from '../.next/Component/Tech'
import Education from '../.next/Component/Education'
// import Project from '../.next/Component/Projects'
// import Page from '../.next/Component/Projects'
import Pages from '../.next/Component/Projects'

const inter = Inter({ subsets: ['latin'] })

export default function Home({profile,repo}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    <HStack>
      <VStack>
        <Profile data={profile}/>
        <Tech/>
        <Education/>
      </VStack>

      <VStack>
{/* <Pages/> */}
{
  repo.items.map((el)=>{

    <Pages key={el.id}  data2={el}/>
})
}
      </VStack>
    </HStack>


    </>
  )

}

export async function getServerSideProps(){

let res  = await fetch("https://api.github.com/users/dkp041297")
// console.log(res.json())
let data = await res.json()

let res2  = await fetch("http://localhost:8080/repo")

let data2 = await res2.json()

  return{
    props:{
      profile:data,
      repo:data2
    }
  }
}

